### ISSUE TITLE
Chrome allows undetected 65535x1

### ISSUE THREAD

**Issue by RReverser** [jhildenbiddle/canvas-size#2] opened 2020-04-21 14:36 UTC
Not sure about other combinations, but it seems that Chrome allows canvas of size 65535x1 nowadays.

This can be currently detected by manually passing this dimension to the `canvasSize.test` method, but isn't detected by `canvasSize.maxWidth` (it still returns 32767x1).

**Comment by jhildenbiddle** [comment] 2020-05-27 07:04
Thanks for the heads up, @RReverser.

When no values are passed to `maxArea()`, `maxWidth()`, or `maxHeight()` the library iterates over previously tested values:

https://github.com/jhildenbiddle/canvas-size/blob/00c259f42c6d33a043ebf17d1c9ccf15520adb15/src/index.js#L12-L71

This optimization was put in place to prevent testing a large number of values unnecessarily. The downside to this approach is that if/when browsers changes their canvas size limits, the test values used in this library will need to be updated.

I've made the necessary change on the `dev` branch. I'm hoping to push a new version out before EOW with [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) and [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) support which will include the fix for this issue.

More to come...

**Comment by RReverser** [comment] 2020-05-27 12:04
> This optimization was put in place to prevent testing a large number of values unnecessarily.

Wouldn't a simple binary search be almost as efficient (or, in most cases, equal, since most values fit on 2^n boundary) but more future-proof?

**Closed** 2020-06-01 00:27 UTC

**Comment by jhildenbiddle** [comment] 2020-06-01 07:16
@RReverser --

If all canvas tests completed instantaneously, yes. The issue is that while an invalid canvas test will fail (almost) immediately, a valid canvas test will take some amount of time dependent upon the canvas size, browser, operating system, hardware, and other activity on the main thread. It is therefore best to perform canvas tests in descending order, failing multiple times until a single canvas test succeeds.

I've created a [demo](https://on690.csb.app/) that will hopefully make this more clear. Consider the following test times taken from this demo using Chrome 83 and a 2015 13" Macbook Pro (3.1GHz i7):

| Method | Result |
| ------ | ------ |
| maxArea() | FAIL: 32767 x 32767 (0 ms)<br>PASS: 16384 x 16384 (428 ms) |
| maxHeight() | FAIL: 1 x 8388607 (0 ms)<br>PASS: 1 x 65535 (0 ms) |
| maxWidth() | FAIL: 4194303 x 1 (0 ms)<br> PASS: 65535 x 1 (0 ms) |
| test() | FAIL: 16387 x 16387 (0 ms)<br>FAIL: 16386 x 16386 (0 ms)<br>FAIL: 16385 x 16385 (0 ms)<br>PASS: 16384 x 16384 (386 ms) |

If a binary search were performed to find the area/height/width limits, multiple successful canvas tests would occur. This is what the current implementation is designed to avoid. That being said, I'm open to any suggestions on how to avoid hard coding canvas dimensions and future-proofing the library.

Thanks!

**Comment by RReverser** [comment] 2020-06-01 11:18
Makes sense, thanks for the explanation. Order of ~400 ms is indeed very slow.
